version: "1"

services:
  hydra-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hydra-service
    networks:
      - hydra-net
    ports:
      - "8000:8000"

  hydra-exporter:
    build:
      context: .
      dockerfile: Dockerfile.exporter
    container_name: hydra-exporter
    networks:
      - hydra-net
    environment:
      HYDRA_URL: http://hydra-service:8000
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - hydra-net
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - hydra-net
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  hydra-net:
    external: true
